apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame
  labels:
    app: boardgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
        # if you're using Istio or similar
    spec:
      containers:
      - name: boardgame-container
        image: 047719649994.dkr.ecr.ap-south-1.amazonaws.com/boardgame:${BUILD_NUMBER}  # Replace with your app image
        ports:
        - containerPort: 8080



---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
spec:
  selector:
    app: boardgame
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort # Change to LoadBalancer or NodePort if needed
