name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build with Maven
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  docker:
    name: Docker Build and Run
    runs-on: self-hosted
    needs: build  # This ensures the docker stage runs after build

    steps:
      - uses: actions/checkout@v4

      - name: Docker Version
        run: docker --version

      - name: Docker Build Image
        run: docker build -t sample:v1 .

      - name: Run Docker Container
        run: docker run -d -p 8080:8080 sample:v1
